layout_spectrum: 1
color:
  saturation: 0.3674111
  lightness: 0.5958745
  brandStrength: 0.5085449
  brandColors:
    - '#E30F0E'
    - '#120D0A'
    - '#992A28'
    - '#F7E8EB'
    - '#EDABAD'
  rhythmicContrast: 0.1585061
typography_spectrum: 0.3088077
name: Crooked Crown
