collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.3674111
  brandStrength: 0.5085449
  lightness: 0.5958745
  brandColors:
    - '#0C0C0C'
    - '#E5E5D9'
    - '#EB1725'
    - '#424242'
    - '#B1B1B1'
  rhythmicContrast: 0.1585061
typography_spectrum: 0.3088077
layout_spectrum: 1
name: Crooked Crown
